In [1]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
print("Reversed:", arr[::-1])


Reversed: [5 4 6 3 2 1]


In [3]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("Flatten with ravel():", array1.ravel())
print("Flatten with flatten():", array1.flatten())


Flatten with ravel(): [1 2 3 2 4 5 1 2 3]
Flatten with flatten(): [1 2 3 2 4 5 1 2 3]


In [5]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print("Arrays are equal:", np.array_equal(arr1, arr2))

Arrays are equal: True


In [9]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

In [11]:
def most_freq(arr):
    vals, counts = np.unique(arr, return_counts=True)
    max_count = np.max(counts)
    most_val = vals[np.argmax(counts)]
    indices = np.where(arr == most_val)[0]
    return most_val, indices

print("Most frequent in x:", most_freq(x))
print("Most frequent in y:", most_freq(y))

Most frequent in x: (1, array([0, 5, 7, 8, 9], dtype=int64))
Most frequent in y: (1, array([0, 1, 2], dtype=int64))


In [13]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Total sum:", np.sum(gfg))
print("Row-wise sum:", np.sum(gfg, axis=1))
print("Column-wise sum:", np.sum(gfg, axis=0))

Total sum: 45
Row-wise sum: [[14]
 [16]
 [15]]
Column-wise sum: [[20  9 16]]


In [15]:
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
print("Diagonal sum:", np.trace(n_array))
eig_vals, eig_vecs = np.linalg.eig(n_array)
print("Eigenvalues:", eig_vals)
print("Eigenvectors:\n", eig_vecs)
print("Inverse:\n", np.linalg.inv(n_array))
print("Determinant:", np.linalg.det(n_array))

Diagonal sum: 176
Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001


In [17]:
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
print("Multiplication 1:\n", np.dot(p1, q1))
print("Covariance 1:\n", np.cov(p1, rowvar=False))

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
print("Multiplication 2:\n", np.dot(p2, q2))
print("Covariance 2:\n", np.cov(p2, rowvar=False))

Multiplication 1:
 [[16 19]
 [26 31]]
Covariance 1:
 [[0.5 0.5]
 [0.5 0.5]]
Multiplication 2:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance 2:
 [[2.33333333 2.33333333]
 [2.33333333 2.33333333]]


In [19]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("Inner product:\n", np.inner(x, y))
print("Outer product:\n", np.outer(x.flatten(), y.flatten()))

from itertools import product
print("Cartesian product:")
print(np.array(list(product(x.flatten(), y.flatten()))))

Inner product:
 [[17 52]
 [13 62]]
Outer product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product:
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [21]:
array = np.array([[1, -2, 3], [-4, 5, -6]])
print("Absolute:\n", np.abs(array))


Absolute:
 [[1 2 3]
 [4 5 6]]


In [23]:
print("Percentile 25, 50, 75 of flattened:", np.percentile(array, [25, 50, 75]))
print("Percentiles per column:\n", np.percentile(array, [25, 50, 75], axis=0))
print("Percentiles per row:\n", np.percentile(array, [25, 50, 75], axis=1))

Percentile 25, 50, 75 of flattened: [-3.5 -0.5  2.5]
Percentiles per column:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles per row:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


In [25]:
print("Mean (flattened):", np.mean(array))
print("Mean (columns):", np.mean(array, axis=0))
print("Mean (rows):", np.mean(array, axis=1))

Mean (flattened): -0.5
Mean (columns): [-1.5  1.5 -1.5]
Mean (rows): [ 0.66666667 -1.66666667]


In [27]:
print("Median (flattened):", np.median(array))
print("Median (columns):", np.median(array, axis=0))
print("Median (rows):", np.median(array, axis=1))

print("Std Dev (flattened):", np.std(array))
print("Std Dev (columns):", np.std(array, axis=0))
print("Std Dev (rows):", np.std(array, axis=1))

Median (flattened): -0.5
Median (columns): [-1.5  1.5 -1.5]
Median (rows): [ 1. -4.]
Std Dev (flattened): 3.8622100754188224
Std Dev (columns): [2.5 3.5 4.5]
Std Dev (rows): [2.05480467 4.78423336]


In [30]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print("Floor:", np.floor(a))
print("Ceil:", np.ceil(a))
print("Trunc:", np.trunc(a))
print("Rounded:", np.round(a))

Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceil: [-1. -1. -0.  1.  2.  2.  3.]
Trunc: [-1. -1. -0.  0.  1.  1.  3.]
Rounded: [-2. -2. -0.  0.  2.  2.  3.]


In [32]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
print("Sorted:", np.sort(array))
print("Sorted indices:", np.argsort(array))
print("4 Smallest:", np.sort(array)[:4])
print("5 Largest:", np.sort(array)[-5:][::-1])

Sorted: [ 10  16  16  52  54  62 453]
Sorted indices: [0 3 4 1 5 2 6]
4 Smallest: [10 16 16 52]
5 Largest: [453  62  54  52  16]


In [34]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print("Integer values:", array[array == np.floor(array)])
print("Float values:", array[array != np.floor(array)])

Integer values: [1. 2. 3. 2.]
Float values: [1.2 2.2]
